name: Deploy to EC2

on:
  push:
    branches:
      - QA  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Copy files to EC2 via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: 13.204.135.75
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/var/www/html"

    - name: Restart Apache
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 13.204.135.75
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: sudo systemctl restart apache2
